# Generated by Django 2.2 on 2020-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profilestatusfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatusfeed',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
